// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.SolarPotential
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("coordinates")]
        public Coordinates Coordinates { get; set; }

        [JsonProperty("usableHours")]
        public UsableHours UsableHours { get; set; }

        [JsonProperty("bestDirection")]
        public string BestDirection { get; set; }

        [JsonProperty("cloudFactor")]
        public double CloudFactor { get; set; }

        [JsonProperty("disclaimer")]
        public string Disclaimer { get; set; }
    }

    public partial class Coordinates
    {
        [JsonProperty("latitude")]
        public double Latitude { get; set; }

        [JsonProperty("longitude")]
        public double Longitude { get; set; }
    }

    public partial class UsableHours
    {
        [JsonProperty("avgDailyUsableSunlightHours")]
        public double AvgDailyUsableSunlightHours { get; set; }

        [JsonProperty("yearlyUsableSunlightHoursRaw")]
        public long YearlyUsableSunlightHoursRaw { get; set; }

        [JsonProperty("adjustedYearlyUsableSunlightHours")]
        public long AdjustedYearlyUsableSunlightHours { get; set; }
    }
}
